# -. _
.PHONY: all compare clean

.SUFFIXES:
.SUFFIXES: .asm .o .gb
.SECONDEXPANSION:

# build virus game
ROM := virus.gb
OBJS := main.o wram.o

# link objects
all: $(ROM)

# assemble source files into objects
# use rgbasm -h to use halts without nops
$(OBJS): $$*.asm $$($$*_dep)
	rgbasm -h -o $@ $<

$(ROM): $(OBJS)
	rgblink -n $(ROM:.gb=.sym) -m $(ROM:.gb=.map) -o $@ $^
	rgbfix -jv -k 01 -l 0x33 -m 0x00 -p 0 -r 02 -t "VIRUS" -i VIRS $@

# remove files generated by the build process
clean:
	rm -f $(ROM) $(OBJS) $(ROM:.gb=.sym)
